checkMode="interval"
intervalMinutes="120"
dailyHour="20"
dailyMinute="30"
weeklyDay="0"
weeklyHour="20"
weeklyMinute="30"
arch="true"
aur="true"
flatpak="false"
widgets="true"
fwupd="false"
feedsEnabled="false"
feedsFetchCount="3"
feeds="https://archlinux.org/feeds/news/"
middleAction="upgradeSystem"
rightAction=""
scrollUpAction=""
scrollDownAction="management"
notifyUpdates="true"
notifyUpdatesAction="true"
notifyEveryBump="true"
notifyNews="true"
notifyNewsAction="false"
notifyErrors="true"
notifySound="true"
notifyPersistent="false"
checkConn="false"
respectMeteredConn="false"
wrapper="yay"
archFlags="--noconfirm"
sudoBin="sudo"
rebootSystem="true"
mirrors="age"
mirrorsAge="14"
mirrorCount="10"
mirrorProgress="true"
dynamicUrl="https://archlinux.org/mirrorlist/?protocol=http&protocol=https&ip_version=4&use_mirror_status=on&country=US&country=CA&country=MX"
flatpakRemoveUnused="true"
flatpakFlags="--assumeyes"
widgetConfirmation="true"
restartShell="false"
restartCommand="systemctl --user restart plasma-plasmashell.service"
trayEnabledByDefault="true"
trayEnabledBy="undefined"
preExec=""
postExec="~/.scripts/clean-cache.sh"
terminal="/usr/bin/konsole"
idleInhibit="false"
tmuxSession="false"
termFont="true"
mngHideFlatpak="false"
mngHideHeaders="false"
mngHideHelp="false"
mngHideNums="false"
fzfOptions=""
hideIconPolicy="0"
selectedIcon="apdatifier-plasmoid"
busyIndicator="pulse"
counterMode="badge"
counterBadgePosition="topRight"
counterSidePosition="left"
counterGapsInner="0"
counterGapsOuter="0"
counterOffsetX="-3"
counterOffsetY="-3"
counterColor="#fa2626"
counterRadius="0"
counterOpacity="8"
counterFontFamily="Noto Sans"
counterFontSize="5"
counterFontBold="true"
pauseBadgePosition="topRight"
updatedBadgePosition="disabled"
badgeOffsetX="-3"
badgeOffsetY="-3"
ownIconsUI="true"
autoHideScrollBar="true"
defaultTab="0"
switchDefaultTab="false"
sorting="true"
showStatusText="true"
showToolBar="true"
searchButton="true"
intervalButton="true"
sortButton="true"
viewButton="true"
managementButton="true"
upgradeButton="true"
checkButton="true"
pinButton="true"
settingsButton="true"
compactInfo="repository"
extendedShowRepository="true"
extendedShowInstallReason="true"
highlightVersionDiff="false"
colorizeInstallReason="false"
tabBarVisible="true"
tabBarTexts="true"
version="v2.9.8"
configMsg="false"
dbPath="${TMPDIR:-/tmp}/checkup-db-$(id -u)"

